### ISSUE TITLE
[FEATURE] Playground.vue should be generated when installing dependencies.

### ISSUE THREAD

**Issue by Michal-Dziedzinski** [vuestorefront/storefront-ui#1308] opened 2020-07-16 13:53 UTC
**Describe how this feature will help us improve**

It may be confusing for the user installing StorefrontUI, he sees an error related to missing `Playground.vue` when trying to run the project and has to create this file manually.

![image](https://user-images.githubusercontent.com/32803679/87678247-019a0f80-c77b-11ea-8711-51d2beb1c1e6.png)

**Describe the solution you'd considered**
@filrak said that earlier this file was generated automatically, so maybe the function just got deleted or something broke. In this case, we need to check the history of the script generating this file.

**Comment by AdamPawlinski** [comment] 2020-07-31 08:05
It looks like part of code responsible for creating Playground.vue in shared/scripts/postinstall.js was removed about year ago, but I wonder if it is still necessary. I haven't seen any error when creating a project. So should we restore it, wdyt @Michal-Dziedzinski ?

**Comment by Baroshem** [comment] 2021-04-13 08:23
Also was not able to reproduce this bug. Closing the issue.

**Closed by Baroshem** 2021-04-13 08:23 UTC
Labels: feature
