### ISSUE TITLE
[BUG] mobile observer issues

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1701] opened 2021-02-12 18:46 UTC
**Describe the bug**
These bug appears when changing between desktop/mobile modes in few components. After few changes these error shows:
  
![image](https://user-images.githubusercontent.com/32042425/107809023-c4c2e500-6d6a-11eb-8206-ee32e6f31801.png)

**How to reproduce**
1. Go to https://vsf-next-demo.storefrontcloud.io/ 
2. try to change mobile/dekstop few times and see the console.

**Expected behavior**
The error not showing.

 
**Actual behavior**

**Code examples**

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by Baroshem** [comment] 2021-03-29 20:03
@AdamPawlinski are you able to reproduce it? I tried it today and wasn't able to see the error in the console

**Comment by AdamPawlinski** [comment] 2021-03-31 06:56
@Baroshem can you try it on VSF Next on CT. As far as I remomeber Justyna found it there.

**Comment by Baroshem** [comment] 2021-03-31 09:16
I couldn't reproduce it even on VSF Next. I went through every page while changing from Mobile to Desktop and the bug wasn't there. Maybe it was fixed before. The only bug that was appearing was a problem with missmatching nodes caused by SfHeader. I am closing this issue for now. If someone manages to reproduce it, the issue can be reopened :)

**Closed** 2022-01-21 14:12 UTC
Labels: bug
