### ISSUE TITLE
[Doc Improvements] adjust view on mobile devices 

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/storefront-ui#1576] opened 2020-12-30 15:40 UTC
**Describe the bug**
There is padding on the body on the mobile view that needs to be removed to the proper view of our designs. 

**How to reproduce**
1. Go to any page example on our storybook
2. Click on mobile view
3. See additional padding 

**Expected behavior**
Mobile view without additional padding

**Comment by KarenEfereyan** [comment] 2021-01-02 03:34
@justyna-13 I am a new contributor to this project. Is this something I can take up?

**Comment by mayashavin** [comment] 2021-01-04 09:24
@KarenEfereyan this is to add custom decorator to remove the default padding caused by storybook. It shouldn't be hard. You can take it ofc. LMK if you want and I will assign this to you

**Comment by mayashavin** [comment] 2021-01-04 10:36
@justyna-13 I don't think I want the padding to be removed, since it doesn't do anything good if removed. For example:
![Screen Shot 2021-01-04 at 12 35 12](https://user-images.githubusercontent.com/6650139/103526317-67916500-4e89-11eb-8bef-8b7dc1ef66e8.png)
This is in production.
@filrak

**Comment by justyna-13** [comment] 2021-01-04 12:40
In my opinion, it would be good to remove this padding because we can have views of our components and pages the same as on figma. For example, a big difference is with SfSteps (but not only) 

with padding:

![Screenshot from 2021-01-04 13-27-17](https://user-images.githubusercontent.com/46591755/103535370-dc1bd200-4e90-11eb-9f8b-4bb72d2bdf33.png)

![Screenshot from 2021-01-04 13-37-31](https://user-images.githubusercontent.com/46591755/103536108-30738180-4e92-11eb-8435-d94694f3d8f1.png)


without:

![Screenshot from 2021-01-04 13-27-24](https://user-images.githubusercontent.com/46591755/103535379-e211b300-4e90-11eb-95a8-15494453ed78.png)

![Screenshot from 2021-01-04 13-37-40](https://user-images.githubusercontent.com/46591755/103536121-34070880-4e92-11eb-8c29-8002136f3fd9.png)


And when it comes to SfTable - it doesn't look good on mobiles and there was a change in design but as someone noticed this won't be valid - as we want to have desktop view without any changes and use HTML tables - https://github.com/vuestorefront/storefront-ui/issues/1496 
So I think we need a better design for SfTable mobile. What do you think? :slightly_smiling_face:

**Comment by KarenEfereyan** [comment] 2021-01-04 13:07
> @KarenEfereyan this is to add custom decorator to remove the default padding caused by storybook. It shouldn't be hard. You can take it ofc. LMK if you want and I will assign this to you

Yes pls. I'll love to work on it

**Comment by mayashavin** [comment] 2021-01-05 07:11
@KarenEfereyan sorry I happened to fix this issue in another PR since it was a quick fix. I can assign you another ticket for documentation if you don't mind :)

**Comment by mayashavin** [comment] 2021-01-05 07:28
@KarenEfereyan Assigned. Please note there are the following things need to be fixed (removed padding) on mobile view:
1. SfMegaMenu
2. SfTable
3. Category
4. SfContentPages
5. SfBannerGrid
6. SfAccordion
7. SfSteps
8. SfColorPicker
9. SfBar
10. SfBanner

If the desktop view of these look ok without padding, you can also use the same style for both. This will lessen the work :).

I recommend you check out the usage of decorators in Storybook 6x. 

LMK if you need help.

**Comment by KarenEfereyan** [comment] 2021-01-10 12:51
So sorry I've been busy getting ready for school. Ill try to get to it today!

**Comment by Baroshem** [comment] 2021-03-18 18:18
@KarenEfereyan
Are you still interested in doing this task? Maybe we could help you with something? ;)

**Comment by KarenEfereyan** [comment] 2021-03-20 15:00
I'm sorry but my laptop crashed.  I haven't been able to buy a new one.
Could you assign someone else?

**Comment by Baroshem** [comment] 2021-07-06 06:27
Could not reproduce the issue. Checked listed components and all seem to look ok. Maybe it was resolved in other PR?

**Comment by justyna-13** [comment] 2021-07-06 06:32
we still have it :) 
![Screenshot from 2021-07-06 08-31-52](https://user-images.githubusercontent.com/46591755/124553159-b322cc80-de34-11eb-9255-77751b5eba65.png)

**Closed** 2021-12-29 06:48 UTC
Labels: docs
