### ISSUE TITLE
[BUG] Demo Searchbar provides error on console

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2402] opened 2022-05-09 11:44 UTC
**Describe the bug**
Trying to use searchbar in Demo SFUI1 provides error on console

**How to reproduce**

1. Go to https://demo-ct.vuestorefront.io/
1. Open Console/DevTools
1. Clean Console
1. Click on searchbar, type "Dress" for example and press "enter"

**Expected behavior**
No error should be shown on the console

**Actual behavior**
Console is providing error. See screenshot

**Screenshots**If applicable, add screenshots to help explain your problem.
![Demo Searchbar error](https://user-images.githubusercontent.com/103260041/167401483-897627e2-6e1b-4f50-a12d-15ece00f1c7c.png)

**Devices (please complete the following information):**

* Device: [Desktop]
* OS: [Windows 11]
* Browser: [Chrome]

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-142) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment] 2022-05-09 20:49
@MaciejWolowski I couldn't reproduce the error. Could you please let me know if there were other circumstances to consider?
![searchbar_demo](https://user-images.githubusercontent.com/32042425/167494314-39493163-6c31-4e95-bb5c-49dd0b650ca9.gif)

**Comment by MaciejWolowski** [comment] 2022-05-10 05:59
@AdamPawlinski I just open new incognito window, go to demo site, open console, click on searchbar, type dress and press enter if i want to share for dress

**Comment by AdamPawlinski** [comment] 2022-05-10 07:38
Ok, I'll try one more time.

**Comment by AdamPawlinski** [comment] 2022-05-30 09:48
Closing this as it is connected with VSF demo implementation.

**Closed by AdamPawlinski** 2022-05-30 09:48 UTC
Labels: bug
