### ISSUE TITLE
[FEATURE] Add color picker to SfProductCard

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#1086] opened 2020-04-20 09:46 UTC
**Describe how this feature will help us improve**
According to designs, we should have a color picker on SfProductCard. It is a common case in e-commerce as well.

![Screenshot from 2020-04-20 11-44-40](https://user-images.githubusercontent.com/41487496/79738072-8e5c3b00-82fc-11ea-8367-e9df6c59e90f.png)

**Comment by pspaczek** [comment] 2020-06-04 13:56
related #881

**Comment by EduardDopler** [comment] 2020-06-23 03:53
@aniamusial Isn't this a duplicate of #881? If there is new info maybe we can add it to the previous issue?

**Closed** 2021-12-02 13:25 UTC
Labels: blocked, feature
