### ISSUE TITLE
[BUG] Storybook Templates Payment/Shipping/ShippingDetails No symbol restrictions in information boxes (maybe feature request)

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2397] opened 2022-04-27 15:31 UTC
**Describe the bug**
THere is no restrictions in what symbols you can put in the boxes. You can put letters in to Zip code and phone number boxes or numbers in city name or person name. Maybe we should restrict that.

**How to reproduce**

1. Go to Storybook
1. Go to section Templates->Payment/Shipping/ShippingDetails 
1. Try to put any data and symbols with mixing letters and numbers in every box

**Expected behavior**
There should be some common sense restrictions like letters only in name or number only i phone number
**Actual behavior**
You can put any symbol to any box. Only CVC code box is different you can only put numbers and letter "e"

**Screenshots**
![Templates Payment No symbol restrictions in information boxes](https://user-images.githubusercontent.com/103260041/165554469-14d2c5eb-492d-41d1-9bac-a03d27732d32.png)

**Devices (please complete the following information):**

* Device: [Desktop]
* OS: [Windows 11]
* Browser: [Chrome]

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-139) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment] 2022-05-09 20:24
I think there is no need to add validation to this component which is only UI without too much logic. It's just a matter of the project which will use this component. Validation can be implemented in many ways so we don't want to force the solution. Wdyt @aniamusial @MaciejWolowski

**Comment by MaciejWolowski** [comment] 2022-05-10 05:57
@AdamPawlinski ok

**Comment by AdamPawlinski** [comment] 2022-05-30 09:49
Closing this, as it is not a bug, explanation above.

**Closed by AdamPawlinski** 2022-05-30 09:49 UTC
Labels: bug
