### ISSUE TITLE
[BUG]: window is not defined due to proactive leaflet loading

### ISSUE THREAD

**Issue by JesseMaxwell** [vuestorefront/storefront-ui#2499] opened 2022-11-09 00:00 UTC
**Describe the bug**
Page crashes because of zealous loading of 3rd-party module leaflet

**How to reproduce**
1. Install 0.13.5
2. Enable SSR
3. Load a Page

**Expected behavior**

**Actual behavior**
What actual happened.

**Code examples**
With Server Side Rendering enabled, Line 230 in `node_modules/leaflet/dist/leaflet-src.js` is hit causing the renderer to crash with the error:
```
ReferenceError
window is not defined
```

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/30010447/200702232-24c5c10b-aec3-4e8e-8ce4-87fba77cce80.png">

Running with Client Side rendering enabled shows the call stack in the browser:
<img width="1903" alt="image" src="https://user-images.githubusercontent.com/30010447/200701624-3d38cd8b-8603-45a7-9d15-a589ef028e72.png">

This is my `yarn.lock`
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/30010447/200701690-3666a788-31be-44e2-9b17-44e0d735088c.png">

**Devices (please complete the following information):**
 - Device: Mac
 - OS: macOS
 - Browser: Chrome

┆Issue is synchronized with this [Jira Task](https://vsf.atlassian.net/browse/SFUI-304) by [Unito](https://www.unito.io)
┆Link To Issue: https://vsf.atlassian.net/browse/SFUI-304

**Comment by bensinca** [comment] 2022-11-09 19:02
As downgrading is not a real 'fix' but thank you @JesseMaxwell. I think on files such as 
https://github.com/vuestorefront/storefront-ui/blob/develop/packages/vue/src/components/organisms/SfStoreLocator/SfStoreLocator.vue#L73

This bit should be on client side. Therefore, could a use of 'require' instead be the solution? 

`import { Icon } from "leaflet";
delete Icon.Default.prototype._getIconUrl;
Icon.Default.mergeOptions({
  iconRetinaUrl: require("leaflet/dist/images/marker-icon-2x.png"),
  iconUrl: require("leaflet/dist/images/marker-icon.png"),
  shadowUrl: require("leaflet/dist/images/marker-shadow.png"),
});
`

**Comment by sheronov** [comment] 2022-11-10 11:05
I also faced with this problem at 0.13.4 and 0.13.5 versions, because of the import from raw "leaflet".

I even don't use [SfStoreLocator ](https://github.com/vuestorefront/storefront-ui/blob/develop/packages/vue/src/components/organisms/SfStoreLocator/SfStoreLocator.vue) component at all.
But it breaks every pages where I have at least one `import { SfSomeComponent } from "@storefront-ui/vue"`

Maybe something wrong with my SSR settings, but now I couldn't just update storefront-ui.
If shouldn't be in this way with patch updates. 

This PR #2428 brought this issue.

**Comment by bensinca** [comment] 2022-11-10 11:27
Potential solutions: https://stackoverflow.com/questions/67824862/how-to-make-a-dynamic-import-in-nuxt/67825061#67825061

```
async mounted() {
  if (process.client) {
    const { icon } = await import('leaflet')
    delete Icon.Default.prototype._getIconUrl;
    Icon.Default.mergeOptions({
      iconRetinaUrl: require("leaflet/dist/images/marker-icon-2x.png"),
      iconUrl: require("leaflet/dist/images/marker-icon.png"),
      shadowUrl: require("leaflet/dist/images/marker-shadow.png"),
    });
  }
},
```

Not tested

**Comment by sheronov** [comment] 2022-11-10 11:37
@bensinca If everything will be in mounted() part then `if (process.client)` is redundant. 

As I know the mounted block doesn't compile in SSR. But I do not use NUXT, just an old vue-storefront-1)

So in my case the `process.client` will generate another frontend error in clients browsers.

**Comment by bensinca** [comment] 2022-11-10 12:39
thanks @sheronov for pointing that out. 

I tested this https://github.com/vuestorefront/storefront-ui/pull/2501 on my dev env  it seems to fix the `window is not defined` error - but I didn't test to see if the component is working :see_no_evil:

**Comment by FRSgit** [comment] 2023-07-05 11:51
Hey everyone!

I'm closing this issue as it seems that #2501 by @bensinca has fixed it. Please open a new ticket if you still can reproduce the problem.

I wanted to inform you that SFUI1 was moved to [LTS mode ](https://docs.storefrontui.io/v1/?path=/docs/storefrontui-lts-policy--page) and we encourage you all to try out the new version - [SFUI2](https://docs.storefrontui.io/v2/)!

Also, don't hesitate to contact us on [our discord server](https://discord.com/invite/vuestorefront) if you have any questions!

**Closed by FRSgit** 2023-07-05 11:51 UTC
Labels: bug, v1.x.x
