### ISSUE TITLE
[BUG] [iOS] Body is scrolling when SfModal is open

### ISSUE THREAD

**Issue by martaradziszewska** [vuestorefront/storefront-ui#1347] opened 2020-07-29 10:47 UTC
**Describe the bug**
on IOS on Safari (v. e.g. 11) when SfModal has content with scrolling, body is scrolling as well. 

**How to reproduce**
1. Go to SfModal
2. Put some content od SfModal to make it scroll
3. Start scrolling down and up
4. See error, body is scrolling as well

**Expected behavior**
Body is not scrolling when SfModal is open

**Devices (please complete the following information):**
 - Device: [ iPhone6]
 - Browser: [safari][version 11.0]

**Comment by AdamPawlinski** [comment] 2020-08-10 11:10
I couldn't reproduce this error. Scrolling behaviour looks fine on safari, but if this happens on specific condition, we can think of adding sfscrollable to modal. 

![modal_safari](https://user-images.githubusercontent.com/32042425/89776750-ca651700-db0a-11ea-9fa6-74b8b76e234b.gif)

Maybe that could help, wdyt @martaradziszewska ?

**Comment by martaradziszewska** [comment] 2020-08-12 11:10
@AdamPawlinski this bug appears on iOS on mobile Safari, could please look at this? As far as I know SFUI use some plugin `body-scroll-lock`. Maybe this can help: https://medium.com/jsdownunder/locking-body-scroll-for-all-devices-22def9615177

**Comment by AdamPawlinski** [comment] 2020-09-08 21:10
I tested it once more and on safari 13 it looks okay for me, because now overlay is not seen 
![image](https://user-images.githubusercontent.com/32042425/92527959-33ce6780-f228-11ea-859a-b3f6cb84b8d8.png) 
but on earlier versions scroll doesn't work at all. So there is still bug of different kind to be fixed.

**Comment by Baroshem** [comment] 2021-06-09 09:48
I also was not able to reproduce this issue. Closing.

**Closed by Baroshem** 2021-06-09 09:48 UTC
Labels: bug
