### ISSUE TITLE
[Bug]: SfChip not handling initial render properly

### ISSUE THREAD

**Issue by rafabernad** [vuestorefront/storefront-ui#2925] opened 2023-07-16 09:23 UTC
### Describe the Bug

When rendering a checked attribute for a SfChip configured with input type radio, checked styles are applied but then dissapear after first render.

### Expected behavior

Element marked as checked should apply checked styles, but it only shows the styles temporarily, then checked styles are removed.

### Steps to reproduce

````
{groups.map((group, idx) => (<ul key={idx} className="flex flex-col md:grid md:grid-cols-3 gap-4 py-4">
  {group.options.map((option, idx) => (
    <li key={idx}>
      <SfChip
        inputProps={{
          type: "radio",
          name: group.name,
          value: option.value,
          checked: selectedOptions.some(
            ({ value }) => {
              return option.value === value
            }
          )
        }}
        className="mr-2 w-full capitalize"
      >
        {option.name}
      </SfChip>
    </li>
  ))}
</ul>))
````

### SFUI version

@storefront-ui/react@2.5.0

### Framework

Next.js

### Node version

20.3.0

### Browser

Chrome

### OS

macOS

### Able to fix / change the documentation?

- [ ] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Szymon-dziewonski** [comment] 2023-07-17 13:14
Hello @rafabernad , Thank you for filing issue, will definitely look into this problem you are facing. However, could you please provide `groups` object, so we would be able to reproduce same setup of component you have ? I would appreciate that a lot :) Have a great day !

**Comment by Szymon-dziewonski** [comment] 2023-07-31 08:57
Hello @rafabernad, thank you for your time, nevertheless unfortunately since we don't have any response from you in some time, then I'm closing this issue. However if you will have full reproduction of this issue I will gladly look over it, I encourage you as well to look over our [vuestorefront discord](https://discord.com/invite/vuestorefront) channel when you can get answers as well :) Have a great day!

**Comment by Szymon-dziewonski** [comment] 2023-07-31 08:57
Hello @rafabernad, thank you for your time, nevertheless unfortunately since we don't have any response from you in some time, then I'm closing this issue. However if you will have full reproduction of this issue I will gladly look over it, I encourage you as well to look over our [vuestorefront discord](https://discord.com/invite/vuestorefront) channel when you can get answers as well :) Have a great day!

**Closed by Szymon-dziewonski** 2023-07-31 08:57 UTC
Labels: bug
